### ISSUE TITLE
Avoid starting a new instance every test?

### ISSUE THREAD

**Issue by bricelam** [microsoft/vs-extension-testing#152]
Is there a way to avoid starting a new instance of devenv.exe every test? When migrating from VsixTesting.Xunit, my CI went from 10 minutes to 30. I suspect this is the reason.

As another side effect of this, I occasionally get the following error when running all tests.

```
System.InvalidOperationException : Test execution was skipped due to a prior exception in the harness.
---- System.InvalidOperationException : VSIX installer failed with exit code: -532462766
```
```
Unhandled Exception: Microsoft.VisualStudio.ExtensionManager.AlreadyInstalledException: Visual Studio Integration Test Service is already installed.
  at Microsoft.VisualStudio.ExtensionManager.InstallModule.CheckIfExtensionRequiresAdditionalOperationForInstall(IExtension extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean installingAsNestedExtension, Boolean allowReplace, Boolean& performExtensionUpdate)
  at Microsoft.VisualStudio.ExtensionManager.InstallModule.ExtensionRequiresAdditionalOperationForInstall(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, InstallFlags flags, Boolean& performExtensionUpdate)
  at Microsoft.VisualStudio.ExtensionManager.InstallModule.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
  at Microsoft.VisualStudio.ExtensionManager.InstallModule.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
  at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.Install(IInstallableExtension extension, InstallFlags installFlags, Version targetedVsVersion)
  at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.Install(IInstallableExtension extension, Boolean perMachine)
  at Microsoft.VisualStudio.VsixInstaller.Installer.InstallImpl(IEnumerable`1 vsixFiles, String rootSuffix, String installationPath)
  at Microsoft.VisualStudio.VsixInstaller.Installer.Install(IEnumerable`1 vsixFiles, String installationPath, String rootSuffix)
  at Microsoft.VisualStudio.VsixInstaller.Installer.Main(String[] args)
```

**Comment by sharwell** [comment]
Instances of devenv are reused for each test collection. By default, xunit makes one collection for each test class, but when using this library you should explicitly configure it to create one for each assembly instead:

https://github.com/microsoft/vs-extension-testing/blob/e22441aa61bf9e330da334660279eb8fba5c8110/src/Microsoft.VisualStudio.Extensibility.Testing.Xunit.IntegrationTests.Shared/XunitAssemblyInfo.cs#L6
