### ISSUE TITLE
System.ArgumentException: The parameter is incorrect

### ISSUE THREAD

**Issue by vasiliisorokin** [microsoft/vs-extension-testing#173]
Getting error during tests in azure pipeline using VSTest version 17.11.0 (x64)

```
Error Message:
   System.InvalidOperationException : Test execution was skipped due to a prior exception in the harness.
---- System.ArgumentException : The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
  Stack Trace:
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at EnvDTE.Commands.Item(Object index, Int32 ID)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

```

**Comment by sorokinva** [comment]
UPD: it happens on `20240912.1.0` windows-2022 image, on `20240811.1.0` it was ok

**Comment by vasiliisorokin** [comment]
UPD: it started to happen on `20240912.1.0` windows-2022 image version in azure pipelines, on `20240811.1.0` it was ok

**Comment by sharwell** [comment]
It's hard to tell where this is being thrown. Are we able to narrow it down, e.g. to this?
https://github.com/microsoft/vs-extension-testing/blob/0b361516389c19f2e297c0480bfcbe4c25a6de89/src/Microsoft.VisualStudio.Extensibility.Testing.Xunit.Shared/Harness/VisualStudioInstance.cs#L258

**Comment by vasiliisorokin** [comment]
Not sure, I suppose its first one. After further investigation - it started to happen on azure runner `windows-2022` after https://github.com/actions/runner-images/pull/10608 update which updates vs version to `17.11.35303.130` (might be not related to vs version but definitely to something that was updated). On previous image version it runs normally.

**Comment by vasiliisorokin** [comment]
Im not sure what causes it, test harness or visual studio or environment, I experienced this only during azure pipeline run and only after image update, I created this issue on their side https://github.com/actions/runner-images/issues/10644
